In [2]:
import numpy as np

In [3]:
A = np.array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]], float)

Complex eigenvalues and eigenvectors, and eigenvectors are not orthogonal

In [4]:
w, v = np.linalg.eig(A)

In [5]:
w

array([ 6.03763849+1.35286176j,  6.03763849-1.35286176j,
       -1.03763849+0.83638338j, -1.03763849-0.83638338j])

In [10]:
v

array([[-0.60349407+0.j        , -0.60349407-0.j        ,
         0.63048552+0.j        ,  0.63048552-0.j        ],
       [-0.23252157+0.3371438j , -0.23252157-0.3371438j ,
        -0.50124509-0.08059567j, -0.50124509+0.08059567j],
       [-0.44119699-0.2603934j , -0.44119699+0.2603934j ,
        -0.2376327 +0.19823402j, -0.2376327 -0.19823402j],
       [-0.43938137-0.11201423j, -0.43938137+0.11201423j,
        -0.4634112 -0.1850128j , -0.4634112 +0.1850128j ]])

In [19]:
np.dot(v[1],v[3])

(0.7146038262207483+0j)

Real eigenvalues for Hermitian matrices, and eigenvectors are orthonormal

In [6]:
A = np.array([[2,1,4,1],[1,4,-1,-1],[4,-1,-1,5],[1,-1,5,3]], float)

In [7]:
w, v = np.linalg.eig(A)

In [8]:
w

array([-5.57408181,  0.82621022,  8.24381194,  4.50405965])

In [9]:
v[0]

array([ 0.38626417, -0.68651368, -0.44271343, -0.42837341])

In [10]:
np.dot(v[1],v[3])

1.1102230246251565e-16

Numpy returns normalized eigenvectors, may be useful for part (e) 

In [30]:
np.linalg.norm(v[0])

1.0